### ISSUE TITLE
Request: KJV with Strongs numbers 

### ISSUE THREAD

**Issue by 40s** [yukuku/androidbible#100]
This has been my favorite Bible app since the day I saw it about two years ago.
The only reason why this is not the only Bible app I have on the phone is because I do not have KJV with Strongs numbers which is essential for Bible study. 
So my data and notes and stuff is split between two different apps. 
If anyone can put the KJV with Strongs numbers I would be really happy. 
Please help me.

**Comment by AlijiEmmanuel-dev** [comment]
Well, I guess I will start working on that myself, if you are interested in working on it with me, let's open a feature branch. 
This is a very solid Bible app, I really love it.

**Comment by 40s** [comment]
Thank you for your interest. 
I would be very happy to be a part of this project. 
Let's start as soon as we can.
