### ISSUE TITLE
Intent to open Bible with a specific verse

### ISSUE THREAD

**Issue by Tazuki** [yukuku/androidbible#16]
Hi yuku,

first thanks for your work.
I dont know if there is another way to ask you this question.
Is it possible to oben androidbible with an Intent to show a specific verse?
Thanks in advance.

god bless you

**Comment by yukuku** [comment]
Yes, it is possible.

Please see 
https://github.com/yukuku/androidbible/blob/develop/AlkitabIntegration/src/main/java/yuku/alkitabintegration/display/Launcher.java

for example methods on how to open specific verses.

**Comment by Tazuki** [comment]
Thank you very much =)
