### ISSUE TITLE
1 verse selected

### ISSUE THREAD

**Issue by rymdemon** [yukuku/androidbible#17]
Setelah alamat bacaan Alkitab dari devotion,  muncul "1 verse selected". Seharusnya kan tidak ada ayat yang dipilih...
:)

**Comment by yukuku** [comment]
Terima kasih atas komentarnya. Devotion yang dibuka itu yang ada lebih dari satu ayat, tapi ketika diklik cuma satu ayat yang kepilih? Kalau bisa tolong sertakan nama renungan dan tanggalnya.

**Comment by rymdemon** [comment]
Renungan yang dipilih Santapan Harian, terjadi setiap hari, sejak versi sebelumnya.
Untuk reproduce issue:
1. Buka Devotion
2. Pilih Santapan Harian
3. Klik link bacaan Alkitab
