### ISSUE TITLE
Perikop Alkitab

### ISSUE THREAD

**Issue by dns** [yukuku/androidbible#18]
Perikop untuk Bahasa Indonesia download dimana ya pak? 
Di source codenya sdh dicari tapi tidak ada.

**Comment by yukuku** [comment]
Betul, memang teks alkitab maupun perikop tidak disertakan dalam source code karena masalah lisensi.

Untuk judul perikop bisa dilihat di http://www.sabda.org/sabdaweb/versions/jtb/
