### ISSUE TITLE
some dir/files missing

### ISSUE THREAD

**Issue by twelfthD** [yukuku/androidbible#21]
i came across with this error ;
building with Andriod Studio 1.3.2
failed to resolve : com.squareup.okhttp:okhttp:2.5.0-SNAPSHOT
failed to resolve : com.squareup.okhttp:okhttp-urlconnection:2.5.0-SNAPSHOT

![error1](https://cloud.githubusercontent.com/assets/14276426/9852250/e75aeb84-5b1a-11e5-98d0-d62fe91b035d.gif)

![build](https://cloud.githubusercontent.com/assets/14276426/9853175/f20a86a2-5b1f-11e5-9a50-2f595e02896c.gif)

**Comment by yukuku** [comment]
okhttp is now at 2.5.0, so they do not publish 2.5.0-SNAPSHOT anymore. 
Fixed in 0e8f5c0. Thanks!
