### ISSUE TITLE
Add History / opened verse

### ISSUE THREAD

**Issue by benyaminl** [yukuku/androidbible#23]
Please add history for the bible app, both quick bible and alkitab. thanks before...

**Comment by yukuku** [comment]
It is already available. Press and hold the verse reference button on the
top (e.g. Genesis 1) and you will see the latest opened verses.

**Comment by benyaminl** [comment]
I see it. Oh God... This's bad for me. Anyway, thanks for replying for it. God Bless!
Benyamin Limanto 《李嘉銘》

Sent from BlackBerry® on 3

-----Original Message-----
