### ISSUE TITLE
I found this while testing it on eclipse

### ISSUE THREAD

**Issue by john7phelyno** [yukuku/androidbible#25]
Description	Resource	Path	Location	Type
error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.NoActionBar'.	themes.xml	/IsiActivity/res/values	line 3	Android AAPT Problem

**Comment by yukuku** [comment]
No idea. Could you try building using Android Studio? Google has stopped
support for Eclipse.
