### ISSUE TITLE
Change pre installed dummy data to full Bible text

### ISSUE THREAD

**Issue by permenko** [yukuku/androidbible#26]
Hi,
i want to create offline Bible application based on your application, how can i change pre insallted dummy data to .yes Bible?

**Comment by yukuku** [comment]
You have to convert it to internal format. Please send me the yet file (not
yes file) and I will prepare the files for inclusion.

**Comment by permenko** [comment]
For example this one. https://www.dropbox.com/s/iqtfp29oa6e0op8/kjv-red.yet?dl=0

**Comment by yukuku** [comment]
A section has been added to https://docs.google.com/document/d/1SGk70g7R3UfN1MTF5jFE9u5bNCY7J9Jeftiq5RjZA0A
called "How to convert YET to internal format" so you can do it easily in the future.

Attached is the converted file from your attached file.

[kjv-red.zip](https://github.com/yukuku/androidbible/files/69546/kjv-red.zip)
