### ISSUE TITLE
Build App Issues

### ISSUE THREAD

**Issue by ideaconceit** [yukuku/androidbible#34]
FAILURE: Build completed with 2 failures.
## 1: Task failed with an exception.
- What went wrong:
  Execution failed for task ':AmbilWarna:compileReleaseJavaWithJavac'.
  
  > When running gradle with java 5, 6 or 7, you must set the path to jdk8, either with property retrolambda.jdk or environment variable JAVA8_HOME
- Try:
  # Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
## 2: Task failed with an exception.
- What went wrong:
  A problem was found with the configuration of task ':AmbilWarna:compileRetrolambdaRelease'.
  
  > Directory 'C:\Users\Desktop\androdaltika\androidbible-develop\AmbilWarna\build\retrolambda\release' specified for property 'inputDir' does not exist.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by yukuku** [comment]
Sorry for not responding to this, this is obsolete and a new build instructions will be written.
