### ISSUE TITLE
Feature Request: Enable ability to scroll from chapter to chapter of same book.

### ISSUE THREAD

**Issue by danyocom** [yukuku/androidbible#38]
Add a preference that would allow the user to  start reading a book/chapter (ex: Genesis 1) and when they scroll (vertically)  to the end of the chapter, the next chapter (ex:Genesis 2) is presented.  

in other words, add a preference to let the user read through a given book of the bible as one continuous document (1 document per book).

**Comment by yukuku** [comment]
@danyocom This is convenient but I think it requires non-trivial amount of work. I will close the issue for now. You can swipe left/right to move to the next/previous chapter.
