### ISSUE TITLE
Please don't require Google Play Services

### ISSUE THREAD

**Issue by oatberry** [yukuku/androidbible#43]
I don't need the features required for Play Services, and I don't have Play Services installed on my phone. The notification asking me to install the Services is getting annoying. Could you please at least add a branch of the code that has this stripped out? (Side note, this would make the app more F-Droid friendly!) Thanks for an otherwise great app!

**Comment by yukuku** [comment]
@oatberry Please take a look at @joielechong's fork. I am sorry that I can't maintain both versions, with and without play services.
