### ISSUE TITLE
Chapters missing!

### ISSUE THREAD

**Issue by ascuccaro** [yukuku/androidbible#45]
In the Reina Valera 1989 version there are some verses missing in Daniel 12 (screenshot attached). I noticed some other verses missing in other books too, but I don't recall exactly which ones. I suggest removing this version from the list or add all the missing text somehow.
![screenshot-](https://cloud.githubusercontent.com/assets/20978858/19311057/2d7834ea-9063-11e6-8a02-8fd25e772422.png)

PS: unrelated, but where could someone suggest versions to be added? Because I'd like for Reina Valera Gomez to be added to the spanish versions.

**Comment by bahiirwa** [comment]
@yukuku Admin: If I could fine the source code files for the yet file. I can add the edits

**Comment by yukuku** [comment]
@ascuccaro Thanks for letting me know about this! 
@bahiirwa ok, please add the edits. Send me a private email to help@bibleforandroid.com mentioning this issue number and I will send you the yet file for editing.

**Comment by ascuccaro** [comment]
There's another chapter with missing verses (same version, of course). Just wanted to let you know.

![192 168 0 147](https://cloud.githubusercontent.com/assets/20978858/20216462/73a5e96e-a7f9-11e6-9cd2-c2cff6a6c105.png)

**Comment by yukuku** [comment]
@ascuccaro This has been fixed since the last update (2016-10-25). Please go to the version list screen and update the rv89 version (it should have the (i) icon).
