### ISSUE TITLE
Opening Quick Bible from external app uses KJV bible

### ISSUE THREAD

**Issue by SamuelPlentz** [yukuku/androidbible#49]
Related to issue #44. When I use the German "Losungen" app (verse of the day) and open the verse in Quick Bible (Popup) it is shown in the KJV bible. If i click on the verse I am redirected to the last bible in use (German). It works different if Quick Bible was in memory when opening the Popup. In this case the last active bible is used.

I would expect to always use the currently active bible or the bible on top of the sorted bible lists. Also it would be great if the popup could be optional, redirecting instantly to the powerful interface of Quick Bible.

**Comment by yukuku** [comment]
@SamuelPlentz I am sorry for the delay in responding to your issue. May I know if you are still interested in this? And could you provide the link to the said "Losungen" app, since I would like to explore how other apps open Quick Bible and so that I can make sure that the user experience feels great.

**Comment by SamuelPlentz** [comment]
Hey, thank you for your answer and thanks a lot for your time.

The "Losungen" app in use can be accessed in [play store](https://play.google.com/store/apps/details?id=de.schalter.losungen) and on [github](https://github.com/schalterDev/Losungen-Android-2).

However the latest versions of Losungen (version 109) and Quick Bible (4.6.3) seem to fix the KJV bible issue.
I am not able to reproduce this part anymore. The last active bible is used. (Even after a restart of my mobile)

Only this open:
> Also it would be great if the popup could be optional, redirecting instantly to the powerful interface of Quick Bible.

**Comment by SamuelPlentz** [comment]
The file in the other git used to open QuickBible:
https://github.com/schalterDev/Losungen-Android-2/blob/master/app/src/main/java/de/schalter/losungen/utils/openExternal/OpenQuickBible.kt

**Comment by yukuku** [comment]
Hi @SamuelPlentz, 

Thank you for the link to the Play Store and also with the source code link so we can examine it closely. We have tested on our devices and found that the behavior is now as expected, where the last selected primary version is used as the popup. Please let us know if you notice that the issue occurs again.
