### ISSUE TITLE
No ddd_revindex.bt in generated internal file.

### ISSUE THREAD

**Issue by joielechong** [yukuku/androidbible#50]
Using YetToInternal.jar to convert from an .yes file not generated any ddd_revindex.bt. I'm using 
[s_BATAKTOBA.PDB](http://download.sabda.org/mobile/pdb/s_BATAKTOBA.PDB) as the source. Yet file is succesfully generated with PdbToYet.jar. Then I edited the generated .yet to fix some error in the format. 

Internal file is successfully created by YetToInternal.jar and I can use it in the application. But without ddd_revindex.bt, the search function can't work as in the https://groups.google.com/forum/#!topic/bibleforandroid/zuZo3QlAfN0. 

So, what should I do to generate the ddd_revindex.bt?

**Comment by yukuku** [comment]
Thanks for the report! We have updated YetToInternal.jar to also create the ddd_revindex_bt.bt file. Please download it from the same link again.

**Comment by joielechong** [comment]
Thank you very much!!. I thought that I need to wait more than a days for your response :P, thank you for the quick response!

Btw, I didn't found any source code for YetToInternal.jar.

**Comment by yukuku** [comment]
The source code is at https://github.com/yukuku/androidbible/blob/before_android_studio/YetToInternal/src/yuku/alkitabconverter/yet/YetToInternal.java

**Comment by joielechong** [comment]
Thank you!
