### ISSUE TITLE
APK for older Android versions

### ISSUE THREAD

**Issue by mcarans** [yukuku/androidbible#58]
Is it possible to provide a package that will install on Android 2.1? Currently, it will not install as the APK is not recognised by Android 2.1.

Is there any feature of the app that prevents it working with older Android versions eg. 2.1? I have a Nook ereader and currently can run either MyBible or MySword on it. It would be great to run Quick Bible.

**Comment by yukuku** [comment]
Yes, you can download older releases at the Releases section of this project. For example, https://github.com/yukuku/androidbible/releases?after=4.0.0 contains the APK for version 3.6.3 that is compatible with Android 2.1.

**Comment by mcarans** [comment]
The link you posted for version 3.6.3 does not have a download for Quick Bible

**Comment by yukuku** [comment]
Go to next page, there is 3.6.2 for Quick Bible.

**Comment by mcarans** [comment]
I tried installing 3.6.2 but it said "installation failed". Any idea why?

**Comment by yukuku** [comment]
No idea. If you run `logcat` when you install the APK, the logcat will show you the details of the error.
