### ISSUE TITLE
Request: External Font Option

### ISSUE THREAD

**Issue by Marhc** [yukuku/androidbible#59]
Please, add a option to include a external font (ttf file).

**Comment by yukuku** [comment]
It is actually possible to add your own font file. Put your font file in the following manner:

Assume that your font file is called XYZ. 
Make a folder called `bible/fonts/XYZ` on the internal storage of your phone (`/sdcard`)
Rename your font file to be `XYZ-Regular.ttf`
Put the file to the folder above. 
When you open the app (force-close it if it is already open), then you should find XYZ on the list of settable fonts.
