### ISSUE TITLE
NestedScrolling support for VerseView

### ISSUE THREAD

**Issue by ghost** [yukuku/androidbible#60]
Hello, I want to use VerseView in CoordinatorLayout. But VerseView extends from ListView. So it can't be nested scrolling. Can you support the nest scrolling for VerseView or extend it to recyclerview?

**Comment by yukuku** [comment]
Yes, you can change it to RecyclerView and submit a pull request. I am
planning to do it but haven't started working on it yet.

**Comment by ghost** [comment]
VerseView is difficult for me to understand. So it is seems difficult for me to do this.
