### ISSUE TITLE
Error when build gradle

### ISSUE THREAD

**Issue by snufflesrea** [yukuku/androidbible#61]
Error:All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html
![capture](https://user-images.githubusercontent.com/15926749/35917506-5acc784e-0c49-11e8-8523-f7a8aca630b7.PNG)

**Comment by yukuku** [comment]
Open the project with Android Studio 2.3, not 3.0.
