### ISSUE TITLE
Bible Plus source code license

### ISSUE THREAD

**Issue by ghost** [yukuku/androidbible#62]
Hello, yuku. I see your project contains Bible Plus package, which is GPL license, but your project is Apache 2.0. I think it is conflict.

**Comment by yukuku** [comment]
You are right! Thank you for pointing out about this. Since you seem to be familiar with licenses, do you think it is better to change the license of this androidbible project, or to rewrite or separate BiblePlus from here?

**Comment by ghost** [comment]
Just as my opinion, change the license of this androidbible project will affect many project base on androidbible and not convenient for use. Can you contact the author of BiblePlus to give a dual license? If not, we should rewrite it. I don't know how to separate BiblePlus from here.

**Comment by yukuku** [comment]
Thanks for the suggestion. I have contacted the BiblePlus author about this.

**Comment by ghost** [comment]
Thank the Lord.
