### ISSUE TITLE
floater not working when I put GotoButton in CoordinatorLayout

### ISSUE THREAD

**Issue by ghost** [yukuku/androidbible#63]
When I use GotoButton in CoordinatorLayout which contains AppBarLayout and BottomNavigationView, the drag guesture of GotoButton is not working, I don't know why but I think it may be caused by CoordinatorLayout behavior and cause the guesture conflict. Can you give me some suggestions for solving  this problem?

**Comment by yukuku** [comment]
CoordinatorLayout intercepts the touch events by `onInterceptTouchEvent`. Probably that's why the gestures are no longer fed into GotoButton.
