### ISSUE TITLE
Logo/Icon Proposal 

### ISSUE THREAD

**Issue by loydjayme25** [yukuku/androidbible#65]

**Comment by loydjayme25** [comment]
Good day sir, here is my design. and i hope you will like it :)

![proposal](https://user-images.githubusercontent.com/37318022/39402876-cd8d7da8-4b9e-11e8-8919-305f8ded199f.png)

![mock-up1](https://user-images.githubusercontent.com/37318022/39402879-d1ded550-4b9e-11e8-9c9d-5ae57ae9007e.png)

**Comment by loydjayme25** [comment]
![color variations](https://user-images.githubusercontent.com/37318022/39403140-4a8ba608-4ba5-11e8-83ab-95ebd0ec1e93.png)

**Comment by yukuku** [comment]
@loydjayme25 Thank you for your icon, however I think the icon is too complex. And I wish that the app does not need to be change, considering there are old people who seems to not like (unannounced) changes on their app collection appearances.
