### ISSUE TITLE
Add instructions for building tools

### ISSUE THREAD

**Issue by samuelallan72** [yukuku/androidbible#68]
There are three main tools, `PdbToYet.jar`, `YetToInternal.jar`, and `YetToYes2.jar`, of which at least the YetToYes2 source is in this repo. However, I can't work out how to build and run these tools from source. It would be nice for some general instructions to be included in the repo.

**Comment by yukuku** [comment]
Those tools are non-Android Java programs. I can't find a way for Android Studio to build jars from the current repo of an Android project. If you switch to the branch `before_android_studio`, you will find there is an artifact configuration that you can build using IntelliJ.
