### ISSUE TITLE
license conflict

### ISSUE THREAD

**Issue by ghost** [yukuku/androidbible#71]
Hello, yukuku. I suggest that you could replace trove4j library, because it is LGPL and not compatible with Apache license which is used for your project.

**Comment by yukuku** [comment]
Thank you @yangshulin2019 for raising this issue. I was not aware of it. 
I have removed the trove4j dependencies in commit 8ba8921724b426734de43963a8869ba336a364c2. I think it is possible that the performance degrades a bit, but I don't think it will be significant, with the recent device performance.
