### ISSUE TITLE
Missin OSIS names for Apocrypha/Deuterocanon

### ISSUE THREAD

**Issue by ajes** [yukuku/androidbible#77]
In: tools/AlkitabConverter/src/main/java/yuku/alkitabconverter/OsisBookNames.javathere is missing part for Apocrypha/Deuterocanon. I believe this file is used when using Yet2Yes with "to:" as address type for xref.

**Comment by yukuku** [comment]
Fixed in 0ccf2ccd (release 4.7). Please let me know if it is still not recognized.
