### ISSUE TITLE
Italization in xref do not work

### ISSUE THREAD

**Issue by ajes** [yukuku/androidbible#78]
Eg:
xref 01 1 2 1 Możliwe jest też tłumaczenie: „tchnienie”, „wiatr” (hebr. @9rû ḥ@7).

This also do not work:
xref 01 1 2 1 Możliwe jest też tłumaczenie: „tchnienie”, „wiatr” (hebr. @@@9rû ḥ@7).

**Comment by yukuku** [comment]
It is working now! It will be released in 4.7.
