### ISSUE TITLE
It seem no Indonesian language (Terjemahan Baru) on Quick Bible

### ISSUE THREAD

**Issue by neroichi** [yukuku/androidbible#82]
Hello. I'm tryng your apps `Quick Bible` as name that i downloaded through F-Droid apps (I have a reason why not to use the app from Play Store)

I have some problems when I'm trying to switch into my language Bible. There is no option for Bible version named `Terjemahan Baru (TB)`. Can you help me with this? Also i know that you are Indonesians. Thanks!

**Comment by yukuku** [comment]
It is true that there is no Indonesian Bible (TB) text on the GitHub repo, but in the Quick Bible app, there should be an option to download it.
