### ISSUE TITLE
alkitab tb + nomor strong

### ISSUE THREAD

**Issue by dennyhalim** [yukuku/androidbible#9]
alkitab terjemahan baru dengan nomor strong akan sangat membantu belajar alkitab.
http://sabdaweb.sabda.org/versions/tb_itl_drf/

terima kasih banyak!
Tuhan Yesus memberkati!

**Comment by yukuku** [comment]
@dennyhalim  untuk saat ini kami tidak memasukkan itu karena belum menemukan cara yang baik untuk menangani nomor Strong yang bertebaran di mana-mana. Apakah Anda masih tertarik dengan fitur ini?

**Comment by dennyhalim** [comment]
ya ini akan sangat membantu pembelajaran
