### ISSUE TITLE
4.9.0 does not let you used "not specified" language .yes files anymore

### ISSUE THREAD

**Issue by dpublic** [yukuku/androidbible#97]
I have local downloaded .yes files that are shown as "not specified" language.
In 4.9.0, from play store, they do not show up in the versions dropdown list so you can not use them.
I manually installed 4.8.1 apk from here and they do show up in the dropdown list so I can use them with that version.

**Comment by yukuku** [comment]
In version 4.9.0, we've made a change so that the app does not have storage access anymore.

Because of that, all version (.yes) files outside the app-private directory won't be accessible. You will need to add them manually using the "+" button on the Version Manager screen.
