### ISSUE TITLE
Mission Notification of "Santapan Harian" on Android 12

### ISSUE THREAD

**Issue by axlchr12** [yukuku/androidbible#98]
I regularly received notification of "Santapan Harian" each day at 08:00am, but recently, the notification is missing.
I check my phone settings and app settings, and nothing changes from default settings.
My phone is the Samsung Galaxy M21, using A12 (API Levels 31, 32).
Any idea what I should do? Is that a bug?
![354474160_1078934279734338_1831420208891579699_n](https://github.com/yukuku/androidbible/assets/29998401/7412947b-b1a5-4cf0-afc5-bbd2d4a24d6c)
![354128471_1338239916787385_6195683607713200443_n](https://github.com/yukuku/androidbible/assets/29998401/c0450e36-2770-4849-bdf0-cb948b1fe3ab)

**Comment by yukuku** [comment]
Hi @AcD08 

Devotion reminders have been removed from the app since 4.9.0. Please use the Google Calendar or Keep app to remind yourself every day.
